In [1]:
import pandas as pd

df = pd.read_csv("../data/processed/tickets_labeled_v1.csv")

df[df["category_rule"] == "service_outage"] \
    .sample(20, random_state=42)[["text", "rule_score"]]

                                                    text  rule_score
17969  its currently 12:33 and i want mcdonalds! what...           0
50550        WHY THE FUCK ARE MY FLIGHTS ALWAYS DELAYED.           0
34006  @ChipotleTweets I feel like this shouldn't be ...           0
66375  @AmazonHelp @115850 Amazon India apps is not o...           0
45486  @USCellularCares Absolutely not.... Really jus...           0
14332  @115888 This immersive experience is so clean ...           0
22490  @AmazonHelp Ayudaaaa\nHice el pedido desde el ...           0
77806  @VirginTrains @385104 Thanks Emma that's great...           0
42215  @SpotifyCares i hate to be a bother but when w...           0
41920  @HPSupport .I want to take this printer to be ...           0
56902  @idea_cares Please do it ASAP. I need my phone...           0
64852  Disgusting customer service from @120474, canc...           0
21973  Oh @Kimpton you have my heart https://t.co/vHr...           0
66161  @AskPlayStation Hi I have WS-37368-7 on my pla...           0
53624  Not a great first experience with @277817 and ...           0
47874  Hey @115722 I just had my service installed an...           0
59812  @Safaricom_Care @118422 @119309 @Safaricom_Car...           0
22756                                  ノートンが正常に機能してくれない。           0
36466  @GoDaddyHelp @221622 Have you tried XenonSite ...           0
71405  @115722 is there any reason on demand would no...           0

In [1]:
import pandas as pd

df = pd.read_csv("../data/processed/tickets_labeled_v1.csv")

# 1) Cuántos service_outage tienen score 0
mask = (df["category_rule"] == "service_outage") & (df["rule_score"] == 0)
print("service_outage con score 0:", mask.sum())

# 2) Muestra 10 ejemplos
df.loc[mask, ["rule_score", "text"]].head(10)

service_outage con score 0: 57456

    rule_score                                               text
1            0  @AppleSupport iOS 11.02 and Watchos4.0: No ico...
2            0  Dear god not again,@AppleSupport https://t.co/...
5            0  trying to buy my kid nibling a keyboard for an...
6            0                  @GWRHelp  https://t.co/EzzirrQuyS
7            0  @131749 recibi llamadas de celulares 311355228...
8            0  @GloCare hi for 2days now I have not being abl...
9            0  @AmazonHelp Are you guys having problems with ...
10           0   WTH HULU!?!?! You LIEEEE https://t.co/4U4nlbGPXX
12           0  @sainsburys Just found a dead fly (ironically,...
13           0  @British_Airways any ideas what a/c  are opera...